version: "3.8"

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - fe_static_data: /usr/share/nginx/html
    depends_on:
      - backend
      - frontend

  frontend:
    build: 
      context: ./Frontend
      dockerfile: ./Frontend/Dockerfile
    container_name: frontend_container
    volumes:
      - fe_static_data: /app/dist
  backend:
    build:
      context: ./Backend
      dockerfile: ./Backend/Dockerfile
    container_name: backend_container 
    environment:
      DATABASE_URL: postgresql+asyncpg://thientai:thientai@db:5432/database_thientai
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CHROMA_DATA_PATH: /app/chroma_data
    depends_on:
      - db
      - redis
    volumes:
      - chroma_data:/app/chroma_data
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: thientai
      POSTGRES_PASSWORD: thientai
      POSTGRES_DB: database_thientai
    volumes:
      - db_data:/var/lib/postgresql/data
      
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
      
volumes: 
  db_data:
  redis_data:
  chroma_data:
  fe_static_data:
