version: "3.8"

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

  frontend:
    build: 
      context: ./Frontend
      dockerfile: ./Frontend/Dockerfile
    container_name: frontend_container

  backend:
    build:
      context: ./Backend
      dockerfile: ./Backend/Dockerfile
    container_name: backend_container 
    environment:
      DATABASE_URL: postgresql+asyncpg://thientai:thientai@db:5432/database_thientai
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
    depends_on:
      - db
      - redis
      - chroma

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: thientai
      POSTGRES_PASSWORD: thientai
      POSTGRES_DB: database_thientai
    volumes:
      - db_data:/var/lib/postgresql/data
      
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  chroma: 
    image: chromadb/chroma:latest 
    container_name: chroma_vector_db
    environment:
      CHROMA_TELEMETRY_ANALYTICS_ON: "False"
    volumes:
      - chroma_data:/chroma/data 
      
volumes: 
  db_data:
  redis_data:
  chroma_data:
