name: Fullstack Deployment

on:
  push:
    branches:
      - develop 

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: thientai
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}
      BE_IMAGE: backend
      FE_IMAGE: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_REPO }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with: 
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/${{ env.BE_IMAGE }}:latest
          platforms: linux/arm64,linux/amd64
          
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/${{ env.FE_IMAGE }}:latest

      - name: Deploy to VPS with Docker compose
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          scripts: |
            PROJECT_PATH="/home/${{ secrets.SSH_USER }}/thientai"
            cd $PROJECT_PATH
          
            # Dùng > (overwrite) cho dòng đầu tiên
            echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}" > .env 
          
            # Dùng >> (append) cho TẤT CẢ các dòng tiếp theo
            echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env
            echo "REDIS_HOST=${{ vars.REDIS_HOST }}" >> .env
            echo "REDIS_DB=${{ vars.REDIS_DB }}" >> .env
            echo "REDIS_DEFAULT_TTL=${{ vars.REDIS_DEFAULT_TTL }}" >> .env
            echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> .env
            echo "REDIS_URL=${{ vars.REDIS_URL }}" >> .env
            echo "REFRESH_TOKEN_EXPIRE_DAYS=${{ vars.REFRESH_TOKEN_EXPIRE_DAYS }}" >> .env
            echo "URL=${{ vars.URL }}" >> .env
            echo "URL_BE=${{ vars.URL_BE }}" >> .env
            echo "URL_IMAGE=${{ vars.URL_IMAGE }}" >> .env
            echo "URL_WS=${{ vars.URL_WS }}" >> .env
            echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            
            docker compose -f docker-compose.yml pull
            
            docker compose -f docker-compose.yml up -d --remove-orphans
            echo "Copying Frontend static files from container to Nginx volume..."
            VOLUME_NAME="thientai_fe_static_data"
            sudo docker cp frontend_container:/app/dist/. $(sudo docker volume inspect $VOLUME_NAME -f '{{.Mountpoint}}')
            docker stop frontend_container || true
            docker rm frontend_container || true
            
            # Dọn dẹp các Image cũ không dùng
            docker image prune -f
