name: Fullstack Deployment

on:
  push:
    branches:
      - develop 

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: ${{ serects.DOCKER_USERNAME }}
      BE_IMAGE: backend
      FE_IMAGE: frontend

    steps:
      - name: Checkout code
        uses: action/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_REPO }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with: 
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/${{ env.BE_IMAGE }}:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/${{ env.FE_IMAGE }}:latest

      - name: Deploy to VPS with Docker compose
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          scripts: |
            PROJECT_PATH="/home/${{ secrets.SSH_USER }}/thientai"
            cd $PROJECT_PATH
            
            docker compose -f docker-compose.yml pull
            
            docker compose -f docker-compose.yml up -d --remove-orphans
            
            docker image prune -f
